### ISSUE TITLE
update packagist entry

### ISSUE THREAD

**Issue by dwenzel** [portrino/px_validation#2]
Could you please update the entry of this package on [packgist.org](https://packagist.org/packages/portrino/px_validation).
This would allow to install it via composer from the default repository.

(This can be done automatically too)

**Comment by EvilBMP** [comment]
Well, the package get's updated automatically on packagist. But my college forgot? to create a tag for version 1.2.0. I'll assign it to him, maybe there is a reason why it's still not tagged.

**Comment by basvandertogt** [comment]
Can you please update packagist with v1.2? Great extension!

**Comment by dwenzel** [comment]
@basvandertogt there is a version 1.2.0 on packagist: https://packagist.org/packages/portrino/px_validation#1.2.0

**Comment by EvilBMP** [comment]
Because I just pushed the tag ;-)
