### ISSUE TITLE
add dependencies from TYPO3

### ISSUE THREAD

**Issue by dwenzel** [portrino/px_validation#3]
`composer.json` should require `typo3/cms-core:^9.5`

**Comment by EvilBMP** [comment]
It should require `typo3/cms-core`, but not only `^9.5` as it is also compatible with older LTS versions.

**Comment by dwenzel** [comment]
@EvilBMP I know that : )  
Unfortunatly the `ext_emconf.php` states otherwise: 
```php
'depends' => [
            'typo3' => '9.5.0 - 9.5.99',
        ],
```
Mismatching requirements would result in an error when trying to install the package.

**Comment by EvilBMP** [comment]
Done in 1.2.1 - sorry for the delay.

**Comment by dwenzel** [comment]
+1
